# Generated by Django 6.0.6 on 2026-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userrequest_target'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrequest',
            name='check_valid_request_type',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('friend', 'friend'), ('project', 'project'), ('file_access', 'file_access')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.CheckConstraint(condition=models.Q(('request_type__in', ['friend', 'project', 'file_access'])), name='check_valid_request_type'),
        ),
    ]
