# Generated by Django 6.0.6 on 2026-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userrequest_check_valid_request_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrequest',
            name='check_valid_request_type',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('friend', 'friend'), ('project', 'project'), ('file_access', 'file_access'), ('move_file_access', 'move_file_access')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.CheckConstraint(condition=models.Q(('request_type__in', ['friend', 'project', 'file_access', 'move_file_access'])), name='check_valid_request_type'),
        ),
    ]
