# Generated by Django 6.0.6 on 2026-07-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userrequest_check_valid_request_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='pk',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
