# Generated by Django 6.0.6 on 2026-07-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userrequest_pk_userrequest_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
