# Generated by Django 6.0.6 on 2026-06-29 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_userprojectrole_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaccess',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskResourceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_path', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accesses', to='projects.projecttask')),
            ],
            options={
                'db_table': 'task_resource_accesses',
                'unique_together': {('task', 'resource_path')},
            },
        ),
    ]
