# Generated by Django 6.0.6 on 2026-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='can_start_calls',
        ),
        migrations.AddField(
            model_name='projectrole',
            name='can_create_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='can_delete_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='can_merge_branches',
            field=models.BooleanField(default=False),
        ),
    ]
