# Generated by Django 6.0.6 on 2026-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projectrole_can_start_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_only_modify_from_app',
            field=models.BooleanField(default=False),
        ),
    ]
