# Generated by Django 6.0.6 on 2026-07-06 09:55

import projects.models
from django.db import migrations, models


def assign_unique_signing_keys(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        project.app_signing_key = projects.models.generate_app_signing_key()
        project.save(update_fields=['app_signing_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_can_only_modify_from_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_signing_key',
            field=models.CharField(default=projects.models.generate_app_signing_key, max_length=64),
        ),
        migrations.RunPython(assign_unique_signing_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='app_signing_key',
            field=models.CharField(default=projects.models.generate_app_signing_key, max_length=64, unique=True),
        ),
    ]
