# Generated by Django 6.0.6 on 2026-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_app_signing_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRepoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_name', models.CharField(max_length=255)),
                ('github_repo_link', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'project_repo_stats',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='repo_stats',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.projectrepostats'),
        ),
    ]
