# Generated by Django 6.0.6 on 2026-07-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectrepostats_project_repo_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='root_link',
        ),
    ]
