# Generated by Django 6.0.6 on 2026-07-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_project_root_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepostats',
            name='github_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
