# Generated by Django 6.0.6 on 2026-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectrepostats_github_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flagged_external_push',
            field=models.BooleanField(default=False),
        ),
    ]
