# Generated by Django 6.0.6 on 2026-07-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_flagged_external_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepostats',
            name='previous_branch_protection',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectrepostats',
            name='protected_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
