# Generated by Django 6.0.2 on 2026-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auditlogaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='can_modify_branches',
            field=models.BooleanField(default=False),
        ),
    ]
