"""
Django settings for devnetwork project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
AUTH_USER_MODEL = 'users.User'
import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
RAPIDAPI_KEY = config("RAPIDAPI_KEY")
RAPIDAPI_HOST = config("RAPIDAPI_HOST")
RAPIDAPI_URL = config("RAPIDAPI_URL")
#SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG',default=False,cast=bool)

ALLOWED_HOSTS = []

ROOT_URLCONF='devnetwork.urls'

# Application definition

DEFAULT_PROJECT_ROLES = {
            'owner': {
                'can_accept_invites': True,
                'can_invite_others': True,
                'can_kick_others': True,
                'can_change_roles': True,
                'can_start_calls': True,
                'can_add_tasks': True,
                'can_modify_tasks': True,
                'can_delete_tasks': True,
                'can_change_project_settings': True,
            },
            'admin': {
                'can_accept_invites': True,
                'can_invite_others': True,
                'can_kick_others': True,
                'can_change_roles': True,
                'can_start_calls': True,
                'can_add_tasks': True,
                'can_modify_tasks': True,
                'can_delete_tasks': False,
                'can_change_project_settings': False,
            },
            'project_manager': {
                'can_accept_invites': True,
                'can_invite_others': True,
                'can_kick_others': False,
                'can_change_roles': False,
                'can_start_calls': True,
                'can_add_tasks': True,
                'can_modify_tasks': True,
                'can_delete_tasks': True,
                'can_change_project_settings': False,
            },
            'developer': {
                'can_accept_invites': False,
                'can_invite_others': False,
                'can_kick_others': False,
                'can_change_roles': False,
                'can_start_calls': True,
                'can_add_tasks': True,
                'can_modify_tasks': True,
                'can_delete_tasks': False,
                'can_change_project_settings': False,
            },
            'tester': {
                'can_accept_invites': False,
                'can_invite_others': False,
                'can_kick_others': False,
                'can_change_roles': False,
                'can_start_calls': True,
                'can_add_tasks': False,
                'can_modify_tasks': True,
                'can_delete_tasks': False,
                'can_change_project_settings': False,
            },
            'viewer': {
                'can_accept_invites': False,
                'can_invite_others': False,
                'can_kick_others': False,
                'can_change_roles': False,
                'can_start_calls': False,
                'can_add_tasks': False,
                'can_modify_tasks': False,
                'can_delete_tasks': False,
                'can_change_project_settings': False,
            }
}

DEFAULT_TECHSTACK_CATEGORIES=['Frontend',
                              'Backend',
                              'Database',
                              'Tools'
                               ]

SEARCH_TYPE = ['ALL','USERS','PROJECTS']

DEFAULT_SECTIONS = {
    'About me': config('ABOUT_ME_DEFAULT'),
    'Skills': config('SKILLS_DEFAULT'),
    'Education': config('EDUCATION_DEFAULT'),
    'Experience': config('EXPERIENCE_DEFAULT'),
    'Certifications': config('CERTIFICATIONS_DEFAULT'),
}
GITHUB_TOKEN = config('GITHUB_TOKEN')

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'users',
    'projects',
    'debug_toolbar',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.cache.CachePanel',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
ASGI_APPLICATION = "devnetwork.asgi.application"
CHANNEL_LAYERS = {
   "default":{
      "BACKEND":"channels_redis.core.RedisChannelLayer",
      "CONFIG":{
          "hosts":[config('REDIS_URL')]
      }
   }
}
#WSGI_APPLICATION = 'devnetwork.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'OPTIONS':{
            'options':'-c search_path=public'
        }
    }
}

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR/'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_TZ = True

TEMPLATES = [
    {
        'BACKEND':'django.template.backends.django.DjangoTemplates',
        'DIRS':[BASE_DIR/'templates'],
        'APP_DIRS':True,
        'OPTIONS':{
            'context_processors': [
                            'django.template.context_processors.debug',
                            'django.template.context_processors.request',
                            'django.contrib.auth.context_processors.auth',
                            'django.contrib.messages.context_processors.messages',
                                    ],
        }
    }
]

CACHES = {
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://127.0.0.1:6379/1",
        "OPTIONS":{
            "CLIENT_CLASS":'django_redis.client.DefaultClient'
        }
    }
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config('ACCESS_TOKEN_EXPIRY_MINUTES', cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config('JWT_REFRESH_EXPIRY_DAYS', cast=int)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": config("JWT_ALGORITHM"),
    "SIGNING_KEY": config('JWT_SIGNING_KEY'),
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",

    "CHECK_REVOKE_TOKEN": False,
    "REVOKE_TOKEN_CLAIM": "hash_password",
    "CHECK_USER_IS_ACTIVE": True,
}

