# Generated by Django 6.0.2 on 2026-05-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_timestamp', models.DateTimeField(db_index=True, default='3000-10-10')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.conversation'),
        ),
    ]
