# Generated by Django 6.0.2 on 2026-05-21 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_conversation_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 21, 20, 3, 38, 423251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 21, 20, 3, 38, 423251, tzinfo=datetime.timezone.utc)),
        ),
    ]
