# Generated by Django 6.0.2 on 2026-05-21 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_conversation_last_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 21, 20, 16, 16, 268498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 21, 20, 16, 16, 268498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 21, 20, 16, 16, 268498, tzinfo=datetime.timezone.utc)),
        ),
    ]
