# Generated by Django 6.0.2 on 2026-05-21 20:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_conversation_creation_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='participated_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 21, 20, 30, 41, 3428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 21, 20, 30, 41, 3428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 21, 20, 30, 41, 5453, tzinfo=datetime.timezone.utc)),
        ),
    ]
