# Generated by Django 6.0.2 on 2026-05-23 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_conversation_is_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 23, 8, 14, 23, 24375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 23, 8, 14, 23, 24375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 23, 8, 14, 23, 25376, tzinfo=datetime.timezone.utc)),
        ),
    ]
