# Generated by Django 6.0.2 on 2026-05-23 10:19

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_conversation_creation_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 23, 10, 19, 39, 161388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 23, 10, 19, 39, 161388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-timestamp'], name='msg_conv_timestamp_idx'),
        ),
    ]
