# Generated by Django 6.0.2 on 2026-05-23 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_conversation_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 23, 10, 20, 31, 922747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 23, 10, 20, 31, 922747, tzinfo=datetime.timezone.utc)),
        ),
    ]
