# Generated by Django 6.0.2 on 2026-05-23 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_conversation_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
